### ISSUE TITLE
asuna.config.js

### ISSUE THREAD

**Issue by swordsman-coder** [ruichengping/asuna-cli#1]
你好 asuna.config.js是用于做什么的

**Comment by ruichengping** [comment]
新增页面或者组件时用到，我在我另一个项目react-webpack-pc中有用到，可以参考一下

**Comment by gjkh0902** [comment]
创建一个测试项目，asuna create asuna-prj
报错了...
Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/asuna-cli/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:537:17)
    at processTimers (internal/timers.js:481:7) {
  code: 'ETIMEDOUT',
  connect: true
}
