### ISSUE TITLE
创建测试项目 asuna create asuna-prj

### ISSUE THREAD

**Issue by gjkh0902** [ruichengping/asuna-cli#2]
Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/asuna-cli/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:537:17)
    at processTimers (internal/timers.js:481:7) {
  code: 'ETIMEDOUT',
  connect: true
}

**Comment by ruichengping** [comment]
多试几次就好了，用的github做的配置仓库，不是太稳定
